product-service
00shiki/naah-project pull request #10
Opened 2024-09-24 13:32 UTC by taketoputa

The whole product-service fetures. Include CRUD products for RBAC.

2024-09-24 17:10 UTC, haryakumuda requested changes
jadi diubah pake grpc kah?

2024-09-24 17:10 UTC, haryakumuda commented on product-service/.env
apa ini .env masuk git

2024-09-24 17:10 UTC, haryakumuda commented on product-service/config/config.go
hati hati pakai automigrate, klo ngubah database, service lain bisa impact

2024-09-26 07:48 UTC, 00shiki approved these changes

2024-09-26 07:51 UTC, haryakumuda approved these changes

2024-09-26 07:57 UTC, merged